language: python
python:
- '3.6'
env:
- TOXENV=flake8
- TOXENV=build
addons:
  apt:
    packages:
       - docker-ce=18.03.1~ce-0~ubuntu
install:
- docker --version
- pip install tox
script: tox
services:
- docker
stages:
- test
- name: pypi
  if: tag IS present
- name: docker
  if: tag IS present
jobs:
  include:
  - stage: pypi
    script: echo "Deploying to PyPi"
    deploy:
      provider: pypi
      distributions: bdist_wheel
      user: rmb938
      password:
        secure: fqnQOZQIdcf/lsKxiRdfYo08MWtCvWU2nnXjWQDxwx2XWQ6OQZn5iG2Ew4JajoKPyhRFEIr3jWLTZ46/PMMmg60+Zra9gbD8ebCRFqk3QwdEd++Q810Q6lvZYhggsQNIKq6/VKRnfDU2CuaPHoDs/kB48cSDoQbrAi7ygp/7VQBV4wgmGgLl6Z6F5IAB/na37ryIgO+Edc21YVwPNANQ0Eohw6BATiti8S6EZXdFildVt18y7WRgzj+0LHYMb5Vg7ejb3HEJwzR6GqiiUxrMRKUYQVApR/wOLvK/hC+7cE3bWn6GacYSAa5B758gTUlcpC4LSI6xvHsNzVvQDwH59aQwvdlgr6SUUA5e2NYLPqk3qDtoTdJlk7xgh+AA+u8B1biWyHq6lfN0KaANUatpKYX/oNWpaf1QcMxsL/Wk/wnyNf2qZrAC9FVxyecfMPdSJsIkhRDenr7RWSiH57d2AF6VRbeEzR72B4nqaG2MHGn0d6AIxuIZ9XT3STy5c/93zObXOW1QpskYP+M61mSHTmojVCbKa2o33ZgABay+SbZJUaJyOeLvcskC0TrK9pZxQ2cZjKg9s3t8RmZsMVc94N7pYKX9VmLuim9ZVwzBPhgo8+vhDwKQi/I4IjxDUWmOmm9iQ50dZ97dihrBdz+zUuKTjS54k1hko0DEW7RuM5o=
      on:
        tags: true
  - stage: docker
    env:
      - secure: jEK0orm5PJtgzGKOJvJYyZKDpE0LWtzqrhLRuZWmq70OiCRJrKj62eaaGC5paIGP1B2RjEVaZvrU7uylFxkG3uSY8ZgBVDJc39zJ5RzOeSWB27UxPv9cXxhPj03ss3GuDYSUorg1RQPV3Zp9/0qSBl+dV0d9z/VCuZhn22HtCIhkgjB4xjBwy/pf4BgEGySwTGugTRNpj/HUIZXYnox/X4dkiFlF8TF3vZL/QGPFFEY+ovjRbSTYGGfU2VSwf84io8j6KyHtDLzypOaNTzCtx9DMKHlMylhp1TGpcLe3DIK+xrjudCZmDGzui2HkcLBHT3i+dL0y3YF8N4R2h05x4sq2h3u1poYGs8IiLoguUQRQ543zPBbwwAnlZF6MeVZNsqBkFn8xodOY+B4Qvt7lcfinf1NBBNMHiGcNUkk1exvoDJ1MUDh4Gtqutrsn7OvlnDPPW/Q5QMR7XNuWbd+1uVIoKR7E9GqBFSjYT13l03ZQP8mBvkTMB39Uwef8W4JrbYPkTLl+PlnbBalwQFxA7peMwnRJseZAB43711fa5xbMk25BjcXOduqUjtq8SKENMEElyZbWGT8ZUTsbG9YfPxoeXAaTECEW3wKaqNHxlNA206Q0Ud7q5n+NEks1NRxfFHPWc5jWhCiYufT/eMBLwipU9euh/PMAqJyW3CamXrg=
      - secure: F2mH2UhKd3dQnw2wsaJgex4AJsQC47PTxsrMIxaSEjBKdNkDyR+yOXjaWz13FY3CLxOPs7NZ+drrCgN63vHKJp3SUkG4oXk/f7E+W0qICni0AK/BfpPKU5Dx1xNnCpv+7rGple+xfARFeyF/ISB6Vyo944iEE4WqbEEPI9Lul5lmEnFbY/zEej/hZbvDk/6oFbn0Kwm+5VyEfDziZ5W0WgbvBm+U6zz15FtDw6rbaRXZk3AcWWAwrK21bS5RjQMvb0LlhDksELa1fKqUHqxeli+pSA5H9HEkUQQY7tt4UAzteOuUDC7Zg/TwjTNnCCrY6i8ELmi/6/sV/uykdXGpakMBg9jjjLtP0HXdg+sLiH0A9GvFKVGKewUTx0o+1C3iwZk68spnACiupjek6pcaO/3Fq+4x3SDmCb31KoQHYo6NmBGVGMu3ta6gOTo03jhUWG1dw/8vzyxzPOnHax5iydlLRGZSfCeDE8SJh3fnu6RBmRZBCAVscA4zEQ+sZjjh4fL6oi9eWJsoOn/IMYnm8SzWS1SsT0l5m6w2+vBuD4e7NM22FaQIALsqEefQY4Af9p6+7eVVnCFBgsJ/v0IweHwN2S8Pz/cJ9xWYah0nhkEWQe1k0z64bkzcj9E2UX9zRD+O44mkLyOhWy+vsh/2t9iQMX+Gy409i9jV+Hkj6Wg=
    script:
      - tox -e build
      - docker build -t rmb938/vmw-cloudinit-metadata:latest .
      - docker tag rmb938/vmw-cloudinit-metadata:latest "rmb938/vmw-cloudinit-metadata:$TRAVIS_TAG"
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push "rmb938/vmw-cloudinit-metadata:$TRAVIS_TAG"
      - docker push rmb938/vmw-cloudinit-metadata:latest

